name: pokerspot_partner_app
description: POKERSPOT PARTNER
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  collection: ^1.17.0
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^14.0.0+1
  flutter_svg: ^2.0.5
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.otf
          weight: 400
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Bold.otf
          weight: 700

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
