name: pokerspot_partner_app
description: POKERSPOT PARTNER
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  card_swiper: ^2.0.4
  collection: ^1.17.0
  dio: ^5.1.2
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^14.0.0+1
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  go_router: ^7.0.0
  iamport_flutter: ^0.10.9
  image_cropper: ^4.0.1
  json_annotation: ^4.8.1
  logger: ^1.3.0
  provider: ^6.0.5
  copy_with_extension: ^5.0.2
  kpostal: ^0.5.1
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  copy_with_extension_gen: ^5.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.otf
          weight: 400
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Bold.otf
          weight: 700

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
