import 'package:flutter/material.dart';
import 'package:pokerspot_partner_app/common/theme/color.dart';

class GameDialogTonerName extends StatelessWidget {
  const GameDialogTonerName({
    super.key,
    this.isAutoGenerated = false,
    required this.name,
  });

  // 이름이 자동 생성된 여부 (자동 생성되기 전 : false / 자동 생성된 후 : true)
  final bool isAutoGenerated;
  final String name;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: double.infinity,
      child: Row(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Expanded(
            child: Text(
              isAutoGenerated ? name : '토너먼트 이름',
              style: Theme.of(context).textTheme.titleMedium!.copyWith(
                    fontWeight: FontWeight.bold,
                    color: isAutoGenerated
                        ? customColorScheme.onSurface2
                        : customColorScheme.onSurface4,
                  ),
            ),
          ),
          const SizedBox(width: 10),
          IconButton(
            onPressed: () {
              Navigator.pop(context);
            },
            icon: Icon(
              Icons.close_rounded,
              color: customColorScheme.onSurface3,
            ),
          ),
        ],
      ),
    );
  }
}
